(eval-when-compile    (require 'color-theme))
(defun ry-color-theme ()
  "Color theme by ry, created 2012-03-03."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "#232323")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "#5A647E")
      (foreground-color . "#E6E1DC")
      (mouse-color . "black"))
     ((align-highlight-change-face . highlight)
      (align-highlight-nochange-face . secondary-selection)
      (apropos-keybinding-face . underline)
      (apropos-label-face italic variable-pitch)
      (apropos-match-face . match)
      (apropos-property-face . bold-italic)
      (apropos-symbol-face . bold)
      (compilation-message-face . underline)
      (goto-address-mail-face . italic)
      (goto-address-mail-mouse-face . secondary-selection)
      (goto-address-url-face . link)
      (goto-address-url-mouse-face . highlight)
      (ispell-highlight-face . isearch)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (snippet-bound-face . bold)
      (snippet-field-face . highlight)
      (tags-tag-face . default)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "#232323" :foreground "#E6E1DC" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 151 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan1"))))
     (compilation-column-number ((t (:foreground "white"))))
     (compilation-error ((t (:foreground "Pink"))))
     (compilation-info ((t (:bold t :foreground "Green1" :weight bold))))
     (compilation-line-number ((t (:foreground "LightSteelBlue"))))
     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
     (completions-annotations ((t (:italic t :slant italic))))
     (completions-common-part ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#E6E1DC" :background "#232323" :stipple nil :height 151))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cursor ((t (:background "#5A647E"))))
     (custom-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:underline t :foreground "violet"))))
     (custom-button-unraised ((t (:underline t))))
     (custom-changed ((t (:background "blue1" :foreground "white"))))
     (custom-comment ((t (:background "dim gray"))))
     (custom-comment-tag ((t (:foreground "gray80"))))
     (custom-documentation ((t (nil))))
     (custom-face-tag ((t (:bold t :weight bold :foreground "light blue"))))
     (custom-group-tag ((t (:bold t :family "Sans Serif" :foreground "light blue" :weight bold :height 1.2))))
     (custom-group-tag-1 ((t (:bold t :family "Sans Serif" :foreground "pink" :weight bold :height 1.2))))
     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
     (custom-link ((t (:underline t :foreground "cyan1"))))
     (custom-modified ((t (:background "blue1" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue1"))))
     (custom-state ((t (:foreground "lime green"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:bold t :foreground "light blue" :weight bold))))
     (custom-visibility ((t (:underline t :foreground "cyan1" :height 0.8))))
     (dropdown-list-face ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil :background "lightyellow" :foreground "black" :height 151))))
     (dropdown-list-selection-face ((t (:foreground "black" :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "unknown" :family "DejaVu Sans Mono" :background "purple" :height 151))))
     (erb-comment-delim-face ((t (:foreground "lightgreen"))))
     (erb-comment-face ((t (:foreground "lightgreen"))))
     (erb-delim-face ((t (:italic t :bold t :foreground "#CC7833" :slant italic :weight bold))))
     (erb-exec-delim-face ((t (:italic t :bold t :slant italic :foreground "#CC7833" :weight bold))))
     (erb-exec-face ((t (:background "#383838"))))
     (erb-face ((t (:background "#383838"))))
     (erb-out-delim-face ((t (:background "#383838" :foreground "#aaffff"))))
     (erb-out-face ((t (:background "#383838"))))
     (escape-glyph ((t (:foreground "cyan"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (flymake-errline ((t (:background "LightSalmon" :foreground "black"))))
     (flymake-warnline ((t (:background "LightSteelBlue" :foreground "black"))))
     (flyspell-duplicate ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
     (flyspell-incorrect ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
     (font-lock-builtin-face ((t (:foreground "#D0D0FF"))))
     (font-lock-comment-delimiter-face ((t (:italic t :slant italic :foreground "#BC9458"))))
     (font-lock-comment-face ((t (:italic t :foreground "#BC9458" :slant italic))))
     (font-lock-constant-face ((t (:foreground "#6D9CBE"))))
     (font-lock-doc-face ((t (:foreground "#A5C261"))))
     (font-lock-doc-string-face ((t (:foreground "#A5C261"))))
     (font-lock-function-name-face ((t (:foreground "#FFC66D"))))
     (font-lock-keyword-face ((t (:foreground "#CC7833"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "#CC7833"))))
     (font-lock-reference-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "#A5C261"))))
     (font-lock-type-face ((t (:foreground "white"))))
     (font-lock-variable-name-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-warning-face ((t (:foreground "Pink"))))
     (fringe ((t (:background "#232323"))))
     (header-line ((t (:background "grey20" :foreground "grey90" :box nil))))
     (help-argument-name ((t (:italic t :slant italic))))
     (highlight ((t (:background "darkolivegreen"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:foreground "Pink"))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "red1"))))
     (isearch ((t (:background "#555555"))))
     (isearch-fail ((t (:background "red4"))))
     (italic ((t (:italic t :slant italic))))
     (lazy-highlight ((t (:background "paleturquoise4"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:underline t :foreground "violet"))))
     (match ((t (:background "RoyalBlue3"))))
     (menu ((t (nil))))
     (minibuffer-prompt ((t (:bold t :foreground "#FF6600" :weight bold))))
     (mode-line ((t (:background "#A5BAF1" :foreground "black"))))
     (mode-line-buffer-id ((t (:background "#A5BAF1" :foreground "black"))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "#1C1C1C" :foreground "#333333" :box (:line-width -1 :color "grey40" :style nil) :weight light))))
     (modeline-mousable ((t (:background "#A5BAF1" :foreground "black"))))
     (modeline-mousable-minor-mode ((t (:background "#A5BAF1" :foreground "black"))))
     (mouse ((t (nil))))
     (next-error ((t (:background "#555577"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (paren-face-match-light ((t (:background "#555577" :foreground "#FFC66D"))))
     (primary-selection ((t (:background "#555577"))))
     (query-replace ((t (:background "#555555"))))
     (region ((t (:background "#555577"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "darkslateblue"))))
     (sgml-namespace ((t (:foreground "#D0D0FF"))))
     (shadow ((t (:foreground "grey70"))))
     (show-paren-match ((t (:background "steelblue3"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (speedbar-button-face ((t (:foreground "green3"))))
     (speedbar-directory-face ((t (:foreground "light blue"))))
     (speedbar-file-face ((t (:foreground "cyan"))))
     (speedbar-highlight-face ((t (:background "sea green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "yellow"))))
     (textile-acronym-face ((t (:foreground "cyan"))))
     (textile-alignments-face ((t (:foreground "cyan"))))
     (textile-blockquote-face ((t (:foreground "ivory4"))))
     (textile-citation-face ((t (:italic t :slant italic))))
     (textile-class-face ((t (:foreground "yellow green"))))
     (textile-code-face ((t (:foreground "ivory3"))))
     (textile-deleted-face ((t (:strike-through t))))
     (textile-emph-face ((t (:italic t :slant italic))))
     (textile-footnote-face ((t (:foreground "orange red"))))
     (textile-footnotemark-face ((t (:foreground "orange red"))))
     (textile-h1-face ((t (:bold t :weight bold :height 2.0))))
     (textile-h2-face ((t (:bold t :weight bold :height 1.75))))
     (textile-h3-face ((t (:bold t :weight bold :height 1.6))))
     (textile-h4-face ((t (:bold t :weight bold :height 1.35))))
     (textile-h5-face ((t (:bold t :weight bold :height 1.2))))
     (textile-h6-face ((t (:bold t :weight bold :height 1.0))))
     (textile-image-face ((t (:foreground "pink"))))
     (textile-inserted-face ((t (:underline t))))
     (textile-lang-face ((t (:foreground "sky blue"))))
     (textile-link-face ((t (:foreground "#8EC65F"))))
     (textile-ol-bullet-face ((t (:foreground "#FC803A"))))
     (textile-pre-face ((t (:foreground "green"))))
     (textile-span-face ((t (:foreground "pink"))))
     (textile-strong-face ((t (:bold t :weight bold))))
     (textile-style-face ((t (:foreground "sandy brown"))))
     (textile-subscript-face ((t (:height 0.8))))
     (textile-superscript-face ((t (:height 1.1))))
     (textile-table-face ((t (:foreground "red"))))
     (textile-ul-bullet-face ((t (:foreground "#FC803A"))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "Sans Serif" :background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (which-func ((t (:foreground "Blue1"))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "dim gray"))))
     (widget-inactive ((t (:foreground "grey70"))))
     (widget-single-line-field ((t (:background "dim gray"))))
     (yaml-tab-face ((t (:bold t :background "red" :foreground "red" :weight bold))))
     (yas/field-debug-face ((t (nil))))
     (yas/field-highlight-face ((t (:background "DimGrey"))))
     (zmacs-region ((t (:background "#555577")))))))
(add-to-list 'color-themes '(my-color-theme  "THEME NAME" "YOUR NAME"))